// ===== 공유 여행 데이터 (상세판) =====
window.TRIP = {
  meta: {
    title: '타이베이 · 신주 2박3일',
    sub: '8/1(토) ~ 8/3(월) · 타이중 IN/OUT · 1인',
  },
  dayColor: {1:'#3ea6ff', 2:'#5ed09a', 3:'#ff8a8a'},
  kmlColor: {1:'ffffa63e', 2:'ff9ad05e', 3:'ff8a8aff'}, // KML: aabbggrr
  dayLabel: {1:'1일차 · 8/1(토)', 2:'2일차 · 8/2(일)', 3:'3일차 · 8/3(월)'},
  dayTheme: {
    1:'타이중 도착 → 신주(TSMC) → 타이베이',
    2:'타이베이 풀데이',
    3:'타이베이 오전 → 타이중 귀국',
  },
  flight: [
    {dir:'가는편', code:'LJ0735', route:'인천 T2 → 타이중 RMQ T1', time:'8/1 07:55 → 09:40', extra:'2h45 직항 · 수하물 15kg'},
    {dir:'오는편', code:'LJ0738', route:'타이중 RMQ T1 → 인천 T2', time:'8/3 17:30 → 21:15', extra:'2h45 직항 · 수하물 15kg'},
  ],
  fare: '₩298,700',
  budget: [
    ['항공 (수하물 포함)', '₩299,000'],
    ['숙박 2박 (타이베이 3성)', '₩170,000'],
    ['고속철 (타이중↔신주↔타이베이)', '₩70,000'],
    ['식비 3일', '₩90,000'],
    ['입장·교통·기타', '₩80,000'],
  ],
  budgetTotal: '≈ ₩709,000',
  priority: [
    '진에어 항공권 (성수기 → 빨리 확정)',
    '타이베이 숙소 2박 (메인역·시먼딩 근처 추천)',
    '고속철(THSR) — 클룩/KKday 외국인 할인 미리',
    '지우펀·예류 근교투어 가면 사전 예약',
    'EasyCard는 현지 공항/편의점서 즉시 구입',
  ],
  tips: [
    ['공항', '타이중 RMQ는 작음. 입국 빠르고, 택시·버스로 고속철역(신우일) 이동 후 북상.'],
    ['EasyCard(悠遊卡)', '지하철·버스·편의점 다 됨. 도착 즉시 사서 충전, 보증금 환불 가능.'],
    ['현금', '야시장·로컬식당은 카드 안 되는 곳 많음. NT$ 현금 꼭 챙기기.'],
    ['푸항또우장(阜杭豆漿)', '타이베이 아침 인기 No.1. 오픈런 필수, 9시 넘으면 줄 폭발.'],
    ['신주/TSMC', '반도체 성지. 단지 외관·과학단지+성황묘 야시장 먹거리 콤보.'],
    ['고속철 vs 일반', '빠른 건 고속철(46~60분, ₩27,900), 싼 건 타철 자강호(2h).'],
    ['수하물', '위탁 15kg + 기내 10kg 별도. 초과 시 온라인 사전구매가 공항보다 쌈. 보조배터리는 기내만.'],
  ],
  // move: 직전 장소에서 이 장소까지 이동 (트리플식)
  places: [
    // ---------- DAY 1 ----------
    {id:1, day:1, time:'09:40', name:'타이중 공항 (RMQ)', nameEn:'Taichung Airport (RMQ)', addr:'No. 1690, Zhonghang Rd, Qingshui, Taichung', cat:'✈️ 도착 · 입국', stay:'40분', lat:24.2647, lng:120.6213,
     move:{mode:'✈️ 비행기', min:'2h45', cost:'-', note:'진에어 LJ0735 인천 출발'},
     desc:'진에어 LJ0735 도착. 작은 공항이라 입국이 빠릅니다. 짐 찾고 → 유심/EasyCard 준비 → 고속철 타이중역(신우일)으로 이동.',
     tips:'<b>바로 할 일</b> ① EasyCard 구입+충전 ② NT$ 현금 환전/인출 ③ 택시 or 시내버스로 고속철역.'},
    {id:2, day:1, time:'10:40', name:'타이중 고속철역 (신우일)', nameEn:'Taichung HSR Station', addr:'No. 8, Zhanqu 2nd Rd, Wuri, Taichung', cat:'🚄 THSR 환승', stay:'30분', lat:24.1124, lng:120.6155,
     move:{mode:'🚕 택시', min:'40분', cost:'NT$450', note:'공항 → 신우일역 (버스 156번도 가능)'},
     desc:'타이중 고속철역에서 북쪽 신주(Hsinchu)행 탑승. 외국인은 클룩/KKday 할인권이 더 저렴. T Express 앱으로 시간표·예매.',
     tips:'<b>고속철</b> 표 없이 가도 15~30분에 1대씩 자주 옴.'},
    {id:3, day:1, time:'11:30', name:'신주 · TSMC 과학단지', nameEn:'Hsinchu Science Park (TSMC)', addr:'Hsinchu Science Park, Hsinchu', cat:'🔬 반도체 성지', stay:'1시간', lat:24.7740, lng:121.0080,
     move:{mode:'🚄 고속철+🚕', min:'25분', cost:'NT$310', note:'타이중→신주역 20분 + 택시 10분'},
     desc:'세계 반도체 1위 TSMC 본진. 신주 과학단지 일대 분위기 체험. (내부 견학 일반 불가, 외관·전시관 중심)',
     tips:'<b>팁</b> 단지는 회사 밀집지구. 가볍게 보고 신주 시내 야시장으로.'},
    {id:4, day:1, time:'13:00', name:'신주 도시성황묘 야시장', nameEn:'Hsinchu City God Temple Night Market', addr:'No. 75, Zhongshan Rd, North District, Hsinchu', cat:'🍜 점심 · 먹거리', stay:'1시간', lat:24.8047, lng:120.9665,
     move:{mode:'🚕 택시', min:'25분', cost:'NT$300', note:'과학단지 → 신주 시내'},
     desc:'신주 대표 먹거리 골목. 공환(摃丸·어묵완자), 미펀(쌀국수) 등 신주 명물로 점심.',
     tips:'<b>현금 필수</b> 로컬 노점은 카드 거의 안 됨. NT$ 소액권 준비.'},
    {id:5, day:1, time:'15:30', name:'타이베이역 · 숙소 체크인', nameEn:'Taipei Main Station', addr:'No. 3, Beiping W Rd, Zhongzheng, Taipei', cat:'🏨 숙소', stay:'1시간', lat:25.0478, lng:121.5170,
     move:{mode:'🚄 고속철', min:'35분', cost:'NT$390', note:'신주 → 타이베이'},
     desc:'타이베이 메인역 근처 숙소 체크인. 교통 허브라 어디든 편함.',
     tips:'<b>숙소 위치</b> 타이베이역·시먼딩·중샤오푸싱 라인이 초보에게 가장 편리.'},
    {id:6, day:1, time:'18:30', name:'스린 야시장 (士林夜市)', nameEn:'Shilin Night Market', addr:'No. 101, Jihe Rd, Shilin, Taipei', cat:'🌃 저녁 · 야시장', stay:'2시간', lat:25.0880, lng:121.5240,
     move:{mode:'🚇 MRT', min:'25분', cost:'NT$30', note:'타이베이역 → 젠탄역(스린)'},
     desc:'타이베이 최대 야시장. 대왕 치킨스테이크(하오따지), 굴전, 버블티 천국. 첫날밤 분위기.',
     tips:'<b>버블티</b> 본고장 쩐주나이차 꼭. 소매치기 주의.'},

    // ---------- DAY 2 ----------
    {id:7, day:2, time:'08:00', name:'푸항또우장 (阜杭豆漿)', nameEn:'Fuhang Soy Milk', addr:'2F, No. 108, Zhongxiao E Rd Sec 1, Huashan Market, Taipei', cat:'🥟 아침 · 오픈런', stay:'1시간', lat:25.0444, lng:121.5240,
     move:{mode:'🚇 MRT', min:'12분', cost:'NT$20', note:'숙소 → 산다오쓰역 5번출구 도보 1분'},
     desc:'타이베이 아침 성지. 화산시장 2층. 더우장(콩국)+딴빙+사오빙요우탸오 조합.',
     tips:'<b>오픈런</b> 8시 전 도착 권장. 9시 넘으면 줄 폭발.'},
    {id:8, day:2, time:'09:30', name:'중정기념당', nameEn:'Chiang Kai-shek Memorial Hall', addr:'No. 21, Zhongshan S Rd, Zhongzheng, Taipei', cat:'🏛️ 랜드마크', stay:'1시간', lat:25.0346, lng:121.5219,
     move:{mode:'🚇 MRT', min:'10분', cost:'NT$20', note:'산다오쓰 → 중정기념당역'},
     desc:'거대한 광장과 위병 교대식으로 유명. 자유광장 패방이 포토스팟.',
     tips:'<b>위병교대</b> 매시 정각(09~17시) 진행.'},
    {id:9, day:2, time:'11:30', name:'융캉제 (永康街)', nameEn:'Yongkang Street', addr:'Yongkang St, Da’an, Taipei', cat:'🍧 맛집거리', stay:'1.5시간', lat:25.0327, lng:121.5295,
     move:{mode:'🚶 도보', min:'12분', cost:'-', note:'중정기념당 → 융캉제 (또는 MRT 1정거장)'},
     desc:'딘타이펑 본점·망고빙수(스무시하우스)·우육면 맛집 밀집. 점심+디저트 한 번에.',
     tips:'<b>딘타이펑</b> 샤오롱바오 원조. 대기 길면 앱 예약.'},
    {id:10, day:2, time:'14:00', name:'타이베이 101', nameEn:'Taipei 101', addr:'No. 7, Xinyi Rd Sec 5, Xinyi, Taipei', cat:'🗼 전망대', stay:'2시간', lat:25.0339, lng:121.5645,
     move:{mode:'🚇 MRT', min:'15분', cost:'NT$25', note:'둥먼역 → 타이베이101역'},
     desc:'타이베이 상징 마천루. 89층 전망대 + 초고속 엘리베이터. 아래 쇼핑몰·푸드코트도 충실.',
     tips:'<b>전망대</b> 해질녘 표가 인기. 클룩 사전 예매 할인.'},
    {id:11, day:2, time:'17:00', name:'시먼딩 (西門町)', nameEn:'Ximending', addr:'Ximending, Wanhua, Taipei', cat:'🛍️ 쇼핑·먹거리', stay:'1.5시간', lat:25.0421, lng:121.5074,
     move:{mode:'🚇 MRT', min:'25분', cost:'NT$30', note:'타이베이101 → 시먼역'},
     desc:'타이베이의 명동. 쇼핑·길거리음식·아종몐셴(굴국수). 젊은 거리 분위기.',
     tips:'<b>아종몐셴</b> 줄 서서 먹는 굴/곱창 국수. 서서 먹는 게 국룰.'},
    {id:12, day:2, time:'19:30', name:'라오허제 야시장 (饒河街)', nameEn:'Raohe Street Night Market', addr:'Raohe St, Songshan, Taipei', cat:'🌃 저녁 · 야시장', stay:'1.5시간', lat:25.0509, lng:121.5773,
     move:{mode:'🚇 MRT', min:'25분', cost:'NT$30', note:'시먼역 → 송산역'},
     desc:'송산역 옆. 후자오빙(후추빵)이 명물. 스린보다 로컬·아담해서 돌기 편함.',
     tips:'<b>후자오빙</b> 입구 화덕집이 시그니처. 송산츠유궁 사원도 옆에.'},

    // ---------- DAY 3 ----------
    {id:13, day:3, time:'09:00', name:'룽산쓰 (龍山寺)', nameEn:'Longshan Temple', addr:'No. 211, Guangzhou St, Wanhua, Taipei', cat:'⛩️ 사원', stay:'1시간', lat:25.0369, lng:121.4999,
     move:{mode:'🚇 MRT', min:'10분', cost:'NT$20', note:'숙소 → 룽산쓰역'},
     desc:'타이베이 최고 오래된 사원. 아침 참배 분위기와 화려한 단청. 근처 보피랴오 옛거리도 함께.',
     tips:'<b>마지막 날</b> 가볍게 둘러보고 기념품·우롱차 쇼핑.'},
    {id:14, day:3, time:'11:30', name:'타이베이역 → 고속철 남하', nameEn:'Taipei Main Station (HSR South)', addr:'No. 3, Beiping W Rd, Zhongzheng, Taipei', cat:'🚄 귀국 이동', stay:'-', lat:25.0478, lng:121.5170,
     move:{mode:'🚇 MRT', min:'10분', cost:'NT$20', note:'룽산쓰 → 타이베이역 (짐 픽업)'},
     desc:'짐 찾아 타이베이역에서 고속철 타이중행 탑승(약 50분). 귀국편 15:00까지 RMQ 공항 도착 목표.',
     tips:'<b>시간 역산</b> 17:30 비행 → 15:00 공항 → 14:00 신우일역 → 13:00 타이베이 출발 안전.'},
    {id:15, day:3, time:'15:00', name:'타이중 공항 (RMQ) 출국', nameEn:'Taichung Airport (RMQ) Departure', addr:'No. 1690, Zhonghang Rd, Qingshui, Taichung', cat:'✈️ 귀국', stay:'-', lat:24.2647, lng:120.6213,
     move:{mode:'🚄 고속철+🚕', min:'1h30', cost:'NT$1,150', note:'타이베이→타이중 고속철 50분 + 택시 35분'},
     desc:'진에어 LJ0738 (17:30 출발). 신우일역→공항 택시 약 30~40분. 면세·체크인 여유있게.',
     tips:'<b>마지막</b> EasyCard 잔액 환불 가능. 위탁 15kg 초과 시 온라인 사전구매가 쌌음.'},
  ],
};
