// ===== 공유 여행 데이터 (상세판) =====
window.TRIP = {
  meta: {
    title: '타이베이 · 신주 2박3일',
    sub: '8/1(토) ~ 8/3(월) · 타이중 IN/OUT · 1인',
  },
  dayColor: {1:'#3ea6ff', 2:'#5ed09a', 3:'#ff8a8a'},
  kmlColor: {1:'ffffa63e', 2:'ff9ad05e', 3:'ff8a8aff'}, // KML: aabbggrr
  dayLabel: {1:'1일차 · 8/1(토)', 2:'2일차 · 8/2(일)', 3:'3일차 · 8/3(월)'},
  dayTheme: {
    1:'타이중 도착 → 신주(미식·동문성) → 타이베이 닝샤야시장',
    2:'타이베이 풀데이 (융캉제·101 석양·라오허)',
    3:'완화(룽산쓰·시먼딩) → 타이중 귀국',
  },
  flight: [
    {dir:'가는편', code:'LJ0735', route:'인천 T2 → 타이중 RMQ T1', time:'8/1 07:55 → 09:40', extra:'2h45 직항 · 수하물 15kg'},
    {dir:'오는편', code:'LJ0738', route:'타이중 RMQ T1 → 인천 T2', time:'8/3 17:30 → 21:15', extra:'2h45 직항 · 수하물 15kg'},
  ],
  fare: '₩298,700',
  budget: [
    ['항공 (수하물 포함)', '₩299,000'],
    ['숙박 2박 (타이베이 3성)', '₩170,000'],
    ['고속철 (타이중↔신주↔타이베이)', '₩70,000'],
    ['식비 3일', '₩90,000'],
    ['입장·교통·기타', '₩80,000'],
  ],
  budgetTotal: '≈ ₩709,000',
  priority: [
    '진에어 항공권 (성수기 → 빨리 확정)',
    '타이베이 숙소 2박 (메인역·시먼딩 근처 추천)',
    '고속철(THSR) — 클룩/KKday 외국인 할인 미리',
    '지우펀·예류 근교투어 가면 사전 예약',
    'EasyCard는 현지 공항/편의점서 즉시 구입',
  ],
  tips: [
    ['공항', '타이중 RMQ는 작음. 입국 빠르고, 택시·버스로 고속철역(신우일) 이동 후 북상.'],
    ['EasyCard(悠遊卡)', '지하철·버스·편의점 다 됨. 도착 즉시 사서 충전, 보증금 환불 가능.'],
    ['현금', '야시장·로컬식당은 카드 안 되는 곳 많음. NT$ 현금 꼭 챙기기.'],
    ['푸항또우장(阜杭豆漿)', '타이베이 아침 인기 No.1. 오픈런 필수, 9시 넘으면 줄 폭발.'],
    ['신주/TSMC', '반도체 성지. 단지 외관·과학단지+성황묘 야시장 먹거리 콤보.'],
    ['고속철 vs 일반', '빠른 건 고속철(46~60분, ₩27,900), 싼 건 타철 자강호(2h).'],
    ['수하물', '위탁 15kg + 기내 10kg 별도. 초과 시 온라인 사전구매가 공항보다 쌈. 보조배터리는 기내만.'],
  ],
  // move: 직전 장소에서 이 장소까지 이동 (트리플식). 블로거 mino0522 + 다수 후기 반영.
  places: [
    // ---------- DAY 1 : 타이중 도착 → 신주 미식 → 타이베이 ----------
    {id:1, day:1, time:'09:40', name:'타이중 공항 (RMQ)', nameEn:'Taichung Airport (RMQ)', addr:'No. 1690, Zhonghang Rd, Qingshui, Taichung', cat:'✈️ 도착 · 입국', stay:'40분', lat:24.2647, lng:120.6213,
     move:{mode:'✈️ 비행기', min:'2h45', cost:'-', note:'진에어 LJ0735 인천 출발'},
     desc:'진에어 LJ0735 도착. 작은 공항이라 입국이 빠릅니다. 짐 찾고 → EasyCard·현금 준비 → 고속철 타이중역(신우일)으로 이동.',
     tips:'<b>바로 할 일</b> ① EasyCard(요요카) 구입+충전 ② NT$ 현금 인출(야시장 카드 안 됨) ③ <b>럭키랜드 추첨</b> 5000.taiwan.net.tw — 3일+ 체류 외국인 5,000NT$ 추첨, 등록해두기.'},
    {id:2, day:1, time:'10:40', name:'타이중 고속철역 (신우일)', nameEn:'Taichung HSR Station', addr:'No. 8, Zhanqu 2nd Rd, Wuri, Taichung', cat:'🚄 THSR 환승', stay:'30분', lat:24.1124, lng:120.6155,
     move:{mode:'🚕 택시', min:'40분', cost:'NT$450', note:'공항 → 신우일역 (버스 156번도 가능)'},
     desc:'타이중 고속철역에서 북쪽 신주(Hsinchu)행 탑승. T Express 앱으로 시간표·예매. 외국인은 클룩/KKday 할인권이 더 저렴.',
     tips:'<b>고속철</b> 표 없이 가도 15~30분에 1대씩 자주 옴. <b>MRT/고속철 내 음식·음료(물도) 금지</b> — 벌금.'},
    {id:3, day:1, time:'11:30', name:'신주 · TSMC 과학단지', nameEn:'Hsinchu Science Park (TSMC)', addr:'Hsinchu Science Park, Hsinchu', cat:'🔬 반도체 성지', stay:'40분', lat:24.7740, lng:121.0080,
     move:{mode:'🚄 고속철+🚕', min:'25분', cost:'NT$310', note:'타이중→신주역 20분 + 택시 10분'},
     desc:'세계 반도체 1위 TSMC 본진. 신주 과학단지 일대 분위기 인증샷. (내부 견학 일반 불가, 외관·전시관 중심)',
     tips:'<b>팁</b> 단지는 회사 밀집지구라 "지나가며 인증" 성격. 가볍게 보고 바로 성황묘 야시장으로 점심.'},
    {id:4, day:1, time:'12:30', name:'신주 도시성황묘 야시장', nameEn:'Hsinchu City God Temple Night Market', addr:'No. 75, Zhongshan Rd, North District, Hsinchu', cat:'🍜 점심 · 미식 끝판왕', stay:'1.5시간', lat:24.8043, lng:120.9665,
     move:{mode:'🚕 택시', min:'20분', cost:'NT$280', note:'과학단지 → 신주 시내 城隍廟'},
     desc:'신주 미식의 핵심. ⭐<b>묘구 야샹판(廟口鴨香飯·훈제오리덮밥)</b> 신주 No.1 / ⭐<b>하이루이 공환(海瑞摃丸·어묵완자탕, 1948)</b> / <b>아청하오 미펀(阿城號 米粉·쌀국수)</b> / <b>린자 러우위안(林家肉圓·고기경단)</b>. 신주=미펀+공환+러우위안 3대명물 한 번에.',
     tips:'<b>현금 필수</b> 노점은 카드 거의 안 됨. <b>합석(共席)</b>이 기본 문화. 밑반찬·물은 유료.'},
    {id:5, day:1, time:'14:00', name:'동문성 (東門城·잉시먼)', nameEn:'Hsinchu East Gate (Yingxi Gate)', addr:'Dongmen St, East District, Hsinchu', cat:'🏯 산책 · 무료', stay:'40분', lat:24.8052, lng:120.9706, badge:'블로그 추가',
     move:{mode:'🚶 도보', min:'9분', cost:'-', note:'성황묘 → 동문성 (신주역 방향)'},
     desc:'1827년 청대 성문 + 해자(護城河) 친수공원. 무료, 야간 조명도 예쁨. 성황묘에서 신주역 가는 길목이라 동선이 자연스러움.',
     tips:'<b>코스</b> 성황묘→동문성 산책→신주 HSR역(시내서 택시 20분, 六家)으로 이동해 타이베이행.'},
    {id:6, day:1, time:'16:30', name:'타이베이역 · 숙소 체크인', nameEn:'Taipei Main Station', addr:'No. 23, Chengdu Rd, Wanhua, Taipei (시먼 추천)', cat:'🏨 숙소', stay:'1시간', lat:25.0478, lng:121.5170,
     move:{mode:'🚄 고속철', min:'35분', cost:'NT$390', note:'신주 → 타이베이 (역까지 택시 20분 별도)'},
     desc:'타이베이 도착, 숙소 체크인. 블로거 추천 <b>Tomorrow Hotel</b>(시먼역 도보 1분, 약 7만원/박, 무료 아이스크림·케이크). 시먼/타이베이역 라인이 초보에게 최적.',
     tips:'<b>숙소 위치</b> Day2·3 동선(완화·중정)과 가까운 시먼딩 추천. 짐 풀고 가볍게 야시장으로.'},
    {id:7, day:1, time:'19:00', name:'닝샤 야시장 (寧夏夜市)', nameEn:'Ningxia Night Market', addr:'Ningxia Rd, Datong, Taipei', cat:'🌃 저녁 · 야시장', stay:'2시간', lat:25.0560, lng:121.5155, badge:'블로그 강추',
     move:{mode:'🚇 MRT', min:'12분', cost:'NT$25', note:'타이베이역 → 솽롄/닝샤'},
     desc:'작지만 알찬 로컬 먹거리 끝판왕. ⭐<b>오징어튀김(스파이시솔트, BHC뿌링클맛 NT$150)</b> 강추 / ⭐<b>망고·망고주스(NT$50/90)</b> 꿀맛. 스린보다 동선 좋고 로컬.',
     tips:'<b>현금</b> 챙기기. 다음날 푸항또우장 오픈런 위해 일찍 마무리.'},

    // ---------- DAY 2 : 타이베이 풀데이 ----------
    {id:8, day:2, time:'08:00', name:'푸항또우장 (阜杭豆漿)', nameEn:'Fuhang Soy Milk', addr:'2F, No. 108, Zhongxiao E Rd Sec 1, Huashan Market, Taipei', cat:'🥟 아침 · 오픈런', stay:'1시간', lat:25.0444, lng:121.5240,
     move:{mode:'🚇 MRT', min:'12분', cost:'NT$20', note:'숙소 → 산다오쓰역 5번출구 도보 1분'},
     desc:'타이베이 아침 성지. 화산시장 2층. 더우장(콩국)+딴빙(달걀전병)+사오빙요우탸오(소병+꽈배기) 조합.',
     tips:'<b>오픈런</b> 8시 전 도착 권장. 9시 넘으면 줄이 어마어마.'},
    {id:9, day:2, time:'09:30', name:'중정기념당', nameEn:'Chiang Kai-shek Memorial Hall', addr:'No. 21, Zhongshan S Rd, Zhongzheng, Taipei', cat:'🏛️ 랜드마크', stay:'1시간', lat:25.0346, lng:121.5219,
     move:{mode:'🚇 MRT', min:'10분', cost:'NT$20', note:'산다오쓰 → 중정기념당역'},
     desc:'거대한 광장과 위병 교대식으로 유명. 자유광장 패방이 포토스팟.',
     tips:'<b>위병교대</b> 매시 정각(09~17시) 진행. 18시 폐장 주의.'},
    {id:10, day:2, time:'11:30', name:'딘타이펑 본점 (鼎泰豐) · 융캉제', nameEn:'Din Tai Fung Original (Yongkang)', addr:'No. 194, Xinyi Rd Sec 2, Da’an, Taipei', cat:'🥟 점심 · 샤오롱바오', stay:'1.5시간', lat:25.0334, lng:121.5298, badge:'블로그 추가',
     move:{mode:'🚶 도보', min:'12분', cost:'-', note:'중정기념당 → 둥먼/융캉제'},
     desc:'샤오롱바오 원조 <b>본점</b>(융캉제 입구). 육즙 끝판왕. 타이베이101 지점은 80분 대기라 본점이 나음. 대기 길면 번호표 받고 융캉제 구경.',
     tips:'<b>대안</b> 양산박 샤오롱바오(시먼)도 5/5 후기. 신라탕(쏸라탕)은 호불호.'},
    {id:11, day:2, time:'13:30', name:'스무시하우스 망고빙수 (思慕昔)', nameEn:'Smoothie House Mango Ice', addr:'No. 15, Yongkang St, Da’an, Taipei', cat:'🍧 디저트', stay:'45분', lat:25.0327, lng:121.5300, badge:'블로그 추가',
     move:{mode:'🚶 도보', min:'3분', cost:'-', note:'딘타이펑 → 융캉제 안'},
     desc:'융캉제 대표 망고빙수 원조집. 여름 필수 코스. 생망고 듬뿍.',
     tips:'<b>꿀팁</b> 1인분도 크니 둘이 나눠먹기 딱. 융캉 우육면(永康牛肉麵)도 근처.'},
    {id:12, day:2, time:'16:30', name:'타이베이 101', nameEn:'Taipei 101', addr:'No. 7, Xinyi Rd Sec 5, Xinyi, Taipei', cat:'🗼 전망대 · 석양', stay:'2.5시간', lat:25.0339, lng:121.5645,
     move:{mode:'🚇 MRT', min:'15분', cost:'NT$25', note:'둥먼역 → 타이베이101역'},
     desc:'타이베이 상징 마천루. 89층 전망대(엘베 34초!) + 660톤 댐퍼(중심추) 볼거리. ⭐<b>석양~야경 타이밍(클룩 18:30 슬롯)</b>이 베스트라는 후기.',
     tips:'<b>선물</b> 근처서 펑리수(치아더 ChiaTe, NT$228/6입) 구매. B1 딘타이펑은 80분 대기라 패스.'},
    {id:13, day:2, time:'19:30', name:'라오허제 야시장 (饒河街)', nameEn:'Raohe Street Night Market', addr:'Raohe St, Songshan, Taipei', cat:'🌃 저녁 · 야시장', stay:'1.5시간', lat:25.0509, lng:121.5773,
     move:{mode:'🚇 MRT', min:'22분', cost:'NT$30', note:'타이베이101 → 송산역'},
     desc:'송산역 옆 3대 야시장. ⭐<b>후추빵(胡椒餅)</b> 입구 화덕집이 명물 강추(고기+후추, 화덕 구이). 치킨롤도 굿. 송산츠유궁 사원 옆.',
     tips:'<b>분해차(우롱)</b> 편의점 NT$35 — 기름진 음식 뒤 현지인처럼. <b>빈랑(檳榔)은 발암물질, 먹지 말 것.</b>'},

    // ---------- DAY 3 : 완화(룽산쓰·시먼딩) → 타이중 귀국 ----------
    {id:14, day:3, time:'09:00', name:'룽산쓰 (龍山寺)', nameEn:'Longshan Temple', addr:'No. 211, Guangzhou St, Wanhua, Taipei', cat:'⛩️ 사원', stay:'45분', lat:25.0369, lng:121.4999,
     move:{mode:'🚇 MRT', min:'10분', cost:'NT$20', note:'숙소 → 룽산쓰역'},
     desc:'타이베이 최고(最古) 사원. 아침 참배 분위기와 화려한 단청. 도교·불교 혼합.',
     tips:'<b>마지막 날</b> 가볍게 둘러보고 우롱차·기념품. 보피랴오·시먼딩과 같은 완화구라 도보권.'},
    {id:15, day:3, time:'09:50', name:'보피랴오 역사거리 (剝皮寮)', nameEn:'Bopiliao Historic Block', addr:'Guangzhou St, Wanhua, Taipei', cat:'📷 옛거리 · 무료', stay:'40분', lat:25.0367, lng:121.5030, badge:'블로그 추가',
     move:{mode:'🚶 도보', min:'3분', cost:'-', note:'룽산쓰 → 보피랴오 (바로 옆)'},
     desc:'청대~일제 옛 거리를 보존한 붉은벽돌 골목. 룽산쓰 바로 옆이라 무료로 사진 명소 추가.',
     tips:'<b>포토</b> 옛 간판·벽돌 골목 인생샷. 영화·드라마 촬영지.'},
    {id:16, day:3, time:'10:40', name:'시먼딩 (西門町)', nameEn:'Ximending', addr:'Ximending, Wanhua, Taipei', cat:'🛍️ 쇼핑 · 길거리음식', stay:'1.5시간', lat:25.0421, lng:121.5068,
     move:{mode:'🚇 MRT', min:'4분', cost:'NT$20', note:'룽산쓰 → 시먼역 (도보 15분도 가능)'},
     desc:'타이베이의 명동. ⭐<b>아종몐셴(阿宗麵線·곱창면선 NT$65, 가쓰오 육수)</b> / ⭐<b>크리스피 밀크도넛(NT$40 강추)</b> / <b>시먼훙러우(西門紅樓·1908 팔각루)</b> / <b>행복당 흑당버블티(NT$120)</b>. 도라에몽 "어디로든 문" 포토.',
     tips:'<b>선물</b> 누가크래커(세인트피터, 커피맛이 인기) 구매. 마지막 쇼핑·점심 해결.'},
    {id:17, day:3, time:'12:30', name:'타이베이역 → 고속철 남하', nameEn:'Taipei Main Station (HSR South)', addr:'No. 3, Beiping W Rd, Zhongzheng, Taipei', cat:'🚄 귀국 이동', stay:'-', lat:25.0478, lng:121.5170,
     move:{mode:'🚇 MRT', min:'6분', cost:'NT$20', note:'시먼역 → 타이베이역 (짐 픽업)'},
     desc:'짐 찾아 타이베이역에서 고속철 타이중행 탑승(약 50분). 귀국편 15:00까지 RMQ 공항 도착 목표.',
     tips:'<b>시간 역산</b> 17:30 비행 → 15:00 공항 → 14:00 신우일역 → 13:00 타이베이 출발 안전.'},
    {id:18, day:3, time:'15:00', name:'타이중 공항 (RMQ) 출국', nameEn:'Taichung Airport (RMQ) Departure', addr:'No. 1690, Zhonghang Rd, Qingshui, Taichung', cat:'✈️ 귀국', stay:'-', lat:24.2647, lng:120.6213,
     move:{mode:'🚄 고속철+🚕', min:'1h30', cost:'NT$1,150', note:'타이베이→타이중 고속철 50분 + 택시 35분'},
     desc:'진에어 LJ0738 (17:30 출발). 신우일역→공항 택시 약 30~40분. 면세·체크인 여유있게.',
     tips:'<b>마지막</b> EasyCard 잔액·보증금 환불 가능. 위탁 15kg 초과 시 온라인 사전구매가 쌌음.'},
  ],
};
